export const mockData = [
  {
    name: "Mike Braham",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "Google",
    website: "https://www.example.com",
    linkedin: "https://www.linkedin.com...",
    status: "Email Found",
    logo: "G",
    phone: "+1 (650) 253-0001",
    email: "mike.braham@google.com",
  },
  {
    name: "Alex Johnson",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "Amazon",
    website: "https://www.sample.com",
    linkedin: "https://www.linkedin.com...",
    status: "Email Found",
    logo: "A",
    phone: "+1 (206) 266-1000",
    email: "alex.johnson@amazon.com",
  },
  {
    name: "Sarah Thompson",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "LinkedIn",
    website: "https://www.testsite.com",
    linkedin: "https://www.linkedin.com...",
    status: "Run condition not met",
    logo: "L",
    phone: "+1 (650) 687-3600",
    email: "sarah.thompson@linkedin.com",
  },
  {
    name: "David Lee",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "Microsoft",
    website: "https://www.demo.com",
    linkedin: "https://www.linkedin.com...",
    status: "Run condition not met",
    logo: "M",
    phone: "+1 (425) 882-8080",
    email: "david.lee@microsoft.com",
  },
  {
    name: "Emily Carter",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "TED",
    website: "https://www.siteexample...",
    linkedin: "https://www.linkedin.com...",
    status: "Email Found",
    logo: "T",
    phone: "+1 (212) 346-2000",
    email: "emily.carter@ted.com",
  },
  {
    name: "James Smith",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "Unilever",
    website: "https://www.webpage.com",
    linkedin: "https://www.linkedin.com...",
    status: "Email Found",
    logo: "U",
    phone: "+1 (201) 894-2230",
    email: "james.smith@unilever.com",
  },
  {
    name: "Laura White",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "Apple",
    website: "https://www.mywebsite.c...",
    linkedin: "https://www.linkedin.com...",
    status: "Run condition not met",
    logo: "A",
    phone: "+1 (408) 996-1010",
    email: "laura.white@apple.com",
  },
  {
    name: "Chris Brown",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "Google",
    website: "https://www.newsite.com",
    linkedin: "https://www.linkedin.com...",
    status: "Run condition not met",
    logo: "G",
    phone: "+1 (650) 253-0002",
    email: "chris.brown@google.com",
  },
  {
    name: "Jessica Green",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "Unilever",
    website: "https://www.uniqueurl.com",
    linkedin: "https://www.linkedin.com...",
    status: "Email Found",
    logo: "U",
    phone: "+1 (201) 894-2231",
    email: "jessica.green@unilever.com",
  },
  {
    name: "Daniel Harris",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "Microsoft",
    website: "https://www.originalsite.c...",
    linkedin: "https://www.linkedin.com...",
    status: "Email Found",
    logo: "M",
    phone: "+1 (425) 882-8081",
    email: "daniel.harris@microsoft.com",
  },
  {
    name: "Megan Clark",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "Apple",
    website: "https://www.freshpage.c...",
    linkedin: "https://www.linkedin.com...",
    status: "Run condition not met",
    logo: "A",
    phone: "+1 (408) 996-1011",
    email: "megan.clark@apple.com",
  },
  {
    name: "Brian Lewis",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "TED",
    website: "https://www.differentdo...",
    linkedin: "https://www.linkedin.com...",
    status: "Email Found",
    logo: "T",
    phone: "+1 (212) 346-2001",
    email: "brian.lewis@ted.com",
  },
  {
    name: "Samantha Hall",
    date: "Oct 12, 2024 at 14:08 PM",
    company: "Google",
    website: "https://www.alternativesi...",
    linkedin: "https://www.linkedin.com...",
    status: "Email Found",
    logo: "G",
    phone: "+1 (650) 253-0003",
    email: "samantha.hall@google.com",
  },
  { name: "Google", date: "", company: "", website: "", linkedin: "", status: "", logo: "", phone: "", email: "" },
  { name: "Amazon", date: "", company: "", website: "", linkedin: "", status: "", logo: "", phone: "", email: "" },
]
